assets:
  - resources

theme:
  logo: resources/images/logo.svg

  sidebar:
    background: "#fbfbfb"
    textColor: "#000000"

examples:
  css:
    - css/styles.css

order:
  - +Variables
  - +Colors
  - +Typography