assets:
  - resources

theme:
  logo: resources/images/logo.svg

  sidebar:
    background: "#fff"
    textColor: "#000000"

  css:
    - css/theme-style.css

  color:
    background: "#fff"
    border: "1px solid #000;"

examples:
  css:
    - css/styles.css

order:
  - +Introduction
  - +Variables
  - +Colors
  - +Typography
